// src/custom.d.ts

// Declare the aws-exports module (JS config generated by AWS Amplify)
declare module './aws-exports' {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const awsconfig: Record<string, any>;
    export default awsconfig;
  }
  
  // Declare the App module if using JS file in a TS project
  declare module './App' {
    const App: React.ComponentType;
    export default App;
  }
  